// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    // Run after `prisma migrate dev` / `prisma db seed`.
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // CLI commands (migrate, introspect, seed, studio) use the DIRECT,
    // non-pooled connection — migrations can't run through Neon's PgBouncer
    // pooler. The app runtime uses the pooled DATABASE_URL via the schema
    // datasource (schema.prisma).
    url: process.env["DIRECT_URL"],
  },
});
